name: rudder_sdk_flutter_example
description: Demonstrates how to use the rudder_sdk_flutter plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  rudder_sdk_flutter: 3.2.0
  rudder_plugin_db_encryption: 1.3.0
  rudder_integration_amplitude_flutter: 2.2.1
  rudder_integration_adjust_flutter: 2.2.0
  rudder_integration_firebase_flutter: 4.3.0
  rudder_integration_braze_flutter: 2.3.0
  rudder_integration_appcenter_flutter: 2.2.0
  rudder_integration_leanplum_flutter: 2.2.0
  rudder_integration_appsflyer_flutter: 1.3.0
  # rudder_integration_kochava_flutter: 2.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   rudder_sdk_flutter:
#     path: "../packages/plugins/rudder_plugin"
#   rudder_sdk_flutter_platform_interface:
#     path: "../packages/plugins/rudder_plugin_interface"
#   rudder_plugin_android:
#     path: "../packages/plugins/rudder_plugin_android"
#   rudder_plugin_ios:
#     path: "../packages/plugins/rudder_plugin_ios"
#   rudder_plugin_web:
#     path: "../packages/plugins/rudder_plugin_web"
#   rudder_plugin_db_encryption:
#     path: "../packages/plugins/rudder_plugin_db_encryption"
#   rudder_integration_amplitude_flutter:
#     path: "../packages/integrations/rudder_integration_amplitude_flutter"
#   rudder_integration_adjust_flutter:
#     path: "../packages/integrations/rudder_integration_adjust_flutter"
#   rudder_integration_firebase_flutter:
#     path: "../packages/integrations/rudder_integration_firebase_flutter"
#   rudder_integration_braze_flutter:
#     path: "../packages/integrations/rudder_integration_braze_flutter"
#   rudder_integration_appcenter_flutter:
#     path: "../packages/integrations/rudder_integration_appcenter_flutter"
#   rudder_integration_leanplum_flutter:
#     path: "../packages/integrations/rudder_integration_leanplum_flutter"
#   rudder_integration_appsflyer_flutter:
#     path: "../packages/integrations/rudder_integration_appsflyer_flutter"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    # - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
