include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    included_file_warning: ignore
#  exclude:
#    - packages/**/example/lib/generated_plugin_registrant.dart

linter:
  rules:
    file_names: false
    library_names: false
    non_constant_identifier_names: false
    constant_identifier_names: false
