name: rudder_plugin_android
version: 2.1.1
description: The RudderStack Flutter SDK allows you to track event data from your app. It can be easily integrated into your Flutter application. After integrating this SDK, you will also send the event data to your preferred analytics destination/s, such as Google Analytics, Amplitude, and more.
homepage: https://github.com/rudderlabs/rudder-sdk-flutter
repository: https://github.com/rudderlabs/rudder-sdk-flutter
issue_tracker: https://github.com/rudderlabs/rudder-sdk-flutter/issues
documentation: https://docs.rudderstack.com/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  rudder_sdk_flutter_platform_interface: ^2.2.0

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter
  test: ^1.19.5
  plugin_platform_interface: ^2.0.0

flutter:
  plugin:
    implements: rudder_sdk_flutter
    platforms:
      android:
        package: com.rudderstack.sdk.flutter
        pluginClass: RudderSdkFlutterPlugin
        dartPluginClass: RudderSdkFlutterAndroid
