name: rudder_sdk_flutter_platform_interface
version: 2.2.0
description: A platform interface for mobile and web sdk
homepage: https://github.com/rudderlabs/rudder-sdk-flutter
repository: https://github.com/rudderlabs/rudder-sdk-flutter
issue_tracker: https://github.com/rudderlabs/rudder-sdk-flutter/issues
documentation: https://docs.rudderstack.com/rudderstack-sdk-integration-guides/rudderstack-flutter-sdk

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.0.0
  intl: ^0.17.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter
  test: ^1.19.5

